"""Versioned, provider-neutral Build Graph foundation."""

from .contracts import (
    ARTIFACT_SOURCES,
    BUILD_ARTIFACT_SCHEMA,
    BUILD_GRAPH_STATE_SCHEMA,
    BUILD_RUN_SCHEMA,
    BuildArtifact,
    BuildCommitResult,
    BuildDefinitionError,
    BuildDiagnostic,
    BuildGraphError,
    BuildGraphState,
    BuildOwnershipViolation,
    BuildReadiness,
    BuildRevisionConflict,
    BuildRun,
    BuildRunConflict,
    BuildTaskState,
    BuildTaskStateError,
    BuildValidationResult,
    DIAGNOSTIC_SEVERITIES,
    DISPOSITIONS,
    REVIEW_POLICIES,
    RUN_STATUSES,
    TASK_STATUSES,
    VALIDATION_STATUSES,
    ArtifactSource,
    DiagnosticSeverity,
    Disposition,
    ReviewPolicy,
    RunStatus,
    TaskStatus,
    ValidationStatus,
    utc_now_iso,
)
from .definition import (
    BuildGraphDefinition,
    BuildTaskDefinition,
    normalize_path,
    path_covers,
    path_tokens,
    paths_overlap,
    validate_task_id,
)
from .service import BuildGraphService
from .store import BuildGraphStore
from .validation import Validator, disposition_for, enforce_ownership, validate_candidate

__all__ = [
    "ARTIFACT_SOURCES",
    "ArtifactSource",
    "BUILD_ARTIFACT_SCHEMA",
    "BUILD_GRAPH_STATE_SCHEMA",
    "BUILD_RUN_SCHEMA",
    "BuildArtifact",
    "BuildCommitResult",
    "BuildDefinitionError",
    "BuildDiagnostic",
    "BuildGraphDefinition",
    "BuildGraphError",
    "BuildGraphService",
    "BuildGraphState",
    "BuildGraphStore",
    "BuildOwnershipViolation",
    "BuildReadiness",
    "BuildRevisionConflict",
    "BuildRun",
    "BuildRunConflict",
    "BuildTaskDefinition",
    "BuildTaskState",
    "BuildTaskStateError",
    "BuildValidationResult",
    "DIAGNOSTIC_SEVERITIES",
    "DiagnosticSeverity",
    "DISPOSITIONS",
    "Disposition",
    "REVIEW_POLICIES",
    "ReviewPolicy",
    "RUN_STATUSES",
    "RunStatus",
    "TASK_STATUSES",
    "TaskStatus",
    "VALIDATION_STATUSES",
    "ValidationStatus",
    "Validator",
    "disposition_for",
    "enforce_ownership",
    "normalize_path",
    "path_covers",
    "path_tokens",
    "paths_overlap",
    "utc_now_iso",
    "validate_candidate",
    "validate_task_id",
]
