"""Edit unconfirmed prose using the existing candidate store and transaction.

No model calls on save, and no old review/delta can approve the edited body.
Review workers capture inputs under the project lock, perform model work outside
it, then recheck both candidate and project authority before committing.
"""
from __future__ import annotations

from copy import deepcopy
from dataclasses import asdict
import hashlib
import json
from types import SimpleNamespace
from typing import Any

from packages.story_core.candidate_draft import CandidateDraft
from packages.story_core.opening_build import execution, runtime as opening
from packages.story_core.persistence.project_locking import project_update_lock
from packages.story_core.persistence.project_transaction import ProjectTransaction


def digest(value: Any) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, ensure_ascii=False,
                                     default=str).encode("utf-8")).hexdigest()


def candidate_authority(candidate: CandidateDraft) -> str:
    return digest(candidate.to_dict())


def review_digest(candidate: CandidateDraft) -> str:
    return digest({"body": candidate.body, "quality": candidate.quality_report,
                   "submission": candidate.submission_payload,
                   "delta": candidate.to_dict().get("continuity_delta")})


def _pending(store, candidate_id, expected=None, *, refresh_author_inputs=False):
    # IDs are generated by CandidateDraft; reject path components at this boundary.
    import re
    if not re.fullmatch(r"cd-[a-f0-9]+", candidate_id):
        raise FileNotFoundError("candidate_not_found")
    candidate = store.candidate_store.get(candidate_id)
    project = store.project()
    ids = {str(project.get("project_id") or ""), str(project.get("active_story_id") or ""),
           str(store.persisted_state().get("story_id") or ""), store.root.name}
    if candidate is None or candidate.project_id.removeprefix("file:") not in {v.removeprefix("file:") for v in ids if v}:
        raise FileNotFoundError("candidate_not_found")
    if candidate.status != "pending":
        raise ValueError("candidate_not_pending")
    if expected is not None and candidate_authority(candidate) != expected:
        raise ValueError("candidate_revision_conflict")
    if candidate.operation != "generate" or candidate.chapter_number != int(store.persisted_state().get("current_chapter") or 0) + 1:
        raise ValueError("candidate_historical_edit_locked")
    if opening.enabled(store):
        previous = candidate.submission_payload.get("opening_authority")
        if refresh_author_inputs:
            current = execution.capture(store)
            # Rechecking may consume sanctioned future-only author-input edits.
            # A changed chapter, plan revision or contract still requires a new
            # candidate; never rebind an old draft to a different chapter plan.
            if not isinstance(previous, dict) or {
                    key: value for key, value in previous.items() if key != "source_fingerprint"
                } != {key: value for key, value in current.items() if key != "source_fingerprint"}:
                raise ValueError("opening_prose_revision_conflict")
            candidate.submission_payload["opening_authority"] = current
        else:
            execution.verify(store, previous)
    return candidate


def save_edit(store, candidate_id: str, *, body: str, expected: str,
              expected_source: str) -> CandidateDraft:
    """Return a new pending candidate; retain the old draft as superseded."""
    if not body.strip() or len(body) > 200000:
        raise ValueError("candidate_body_invalid")
    with project_update_lock(store.root):
        current = _pending(store, candidate_id, expected, refresh_author_inputs=True)
        if execution.source_fingerprint(store) != expected_source:
            raise ValueError("candidate_source_changed")
        if current.body == body:
            return current
        payload = deepcopy(current.submission_payload)
        # Keep only source planning. Every body-derived field must be rebuilt.
        authority = payload.get("opening_authority")
        director = payload.get("director_artifact")
        payload = {"body": body, "chapter_number": current.chapter_number,
                   "chapter_title": current.chapter_title}
        if authority:
            payload["opening_authority"] = authority
        if director:
            payload["director_artifact"] = director
        candidate = CandidateDraft.create(
            project_id=current.project_id, chapter_number=current.chapter_number,
            chapter_title=current.chapter_title, body=body,
            submission_payload=payload, operation="generate",
            revision_history=[*current.revision_history, {"candidate_id": current.candidate_id,
                                                         "reason": "author_edit"}],
        )
        candidate.review_binding = {"state": "unchecked", "source": expected_source,
                                    "parent": current.candidate_id}
        with ProjectTransaction.create(store.root, snapshot_store=store.snapshot_store,
                managed_paths=[], managed_directories=[store.candidate_store.directory]):
            store.candidate_store.save_latest(candidate)
        return candidate


def assert_review_current(store, candidate: CandidateDraft) -> None:
    binding = candidate.review_binding
    if not binding:
        return  # Existing unedited candidates retain their established checks.
    if binding.get("state") != "checked" or binding.get("result") != review_digest(candidate):
        raise ValueError("candidate_review_required")
    if binding.get("source") != execution.source_fingerprint(store):
        raise ValueError("candidate_review_source_changed")


def recheck(store, candidate_id: str, *, expected: str,
            consistency_runtime=None, fact_extractor=None) -> CandidateDraft:
    """Recheck this exact body, using the existing Canon Review and extractor.

    The caller owns the existing generation-job lifecycle. Failed/incomplete
    reviews leave the edited candidate untouched and unconfirmable.
    """
    from packages.story_core.agents import pipeline
    from packages.story_core.agents.contracts import DirectorArtifact
    from packages.story_core.agents.consistency import focused_consistency_review
    from packages.story_core.agents.fact_extractor import FactExtractor, FactExtractorContext
    from packages.story_core.canon.review_snapshot import build_canon_review_snapshot
    from packages.story_core.models import StoryState
    from packages.story_core.modular_bundle_adapter import adapt_modular_bundle_to_legacy
    from packages.story_core.prompt_templates import prompt_template_scope
    from packages.story_core.prompt_call_log import prompt_call_recording

    with project_update_lock(store.root):
        candidate = _pending(store, candidate_id, expected, refresh_author_inputs=True)
        source = execution.source_fingerprint(store)
        candidate.review_binding = {**candidate.review_binding, "state": "unchecked", "source": source}
        candidate.review_binding.pop("result", None)
        store.candidate_store.save(candidate)
        expected = candidate_authority(candidate)
        saved_director = candidate.submission_payload.get("director_artifact")
        if not saved_director:
            raise ValueError("candidate_review_planning_missing")
        director = DirectorArtifact.model_validate(saved_director)
        from packages.story_core.opening_build.execution import verify_writer_planning
        verify_writer_planning(store.root, director)
        context = pipeline._ensure_writer_context(project_root=store.root,
            chapter_number=candidate.chapter_number, director_artifact=director)
        canon = pipeline._ensure_canon_service(store._load_canon_registry(), store.root)
        canon_view = pipeline._canon_view_for(canon)
        snapshot = build_canon_review_snapshot(project_root=store.root,
            chapter_number=candidate.chapter_number, registry=canon.registry,
            continuity_facts=list(context.continuity_facts or []),
            character_cards=list(context.character_cards or []),
            entity_cards=list(context.entity_cards or []), world_rules=list(context.world_rules or []))
        preflight, prepared = pipeline._preflight_entities(canon, director)
        context = pipeline._add_prepared_entities_to_context(context, prepared)
        state = store._generation_state(store.state())
        story = StoryState.model_validate(store._story_state_payload_for_direction(
            state, store.project(), candidate.chapter_number))
        if opening.enabled(store):
            story = execution.bind_story_planning(store, story)
        snapshot["author_requirements"] = list(story.author_constraints) + (
            list(director.outline_contract.must_not_write) if director.outline_contract else [])

    # No project lock while the runtime is contacted. Unavailability is NOT pass.
    with prompt_template_scope(store.prompt_template_object, store.prompt_template_source), prompt_call_recording(store.prompt_call_log()):
        findings = focused_consistency_review(candidate.body, director_artifact=director,
            active_facts=list(snapshot.get("facts") or []),
            character_states=list(snapshot.get("characters") or []), canon_snapshot=snapshot,
            runtime=consistency_runtime or pipeline._default_consistency_runtime(store.root))
    if any(f.code in {"consistency.unavailable", "consistency.invalid_response"} for f in findings):
        raise ValueError("candidate_review_unavailable")
    findings.extend(pipeline._deterministic_prose_findings(candidate.body,
        list(context.character_cards or []), rewrite_guidance="\n".join(story.author_constraints)))
    if director.outline_contract is not None and director.outline_contract.planned_hook:
        hook_review = pipeline.review_chapter_hook(candidate.body,
            pipeline.parse_chapter_end_hook(director.hook), None)
        if hook_review.get("scores", {}).get("hook_landed") == 5:
            findings.append(pipeline.ConsistencyFinding(code="chapter.hook_not_landed",
                message="正文末段尚未落实本章安排中的悬念。", source="hook", blocking=True))
    delta = (fact_extractor or FactExtractor()).extract(FactExtractorContext(
        body=candidate.body, chapter_number=candidate.chapter_number,
        director_artifact=director, canon_view=canon_view,
        continuity_facts=list(context.continuity_facts or []),
        candidate_entities=[{**dict(card), "kind": "character"}
            for card in context.character_cards if isinstance(card, dict)]
            + [dict(card) for card in context.entity_cards if isinstance(card, dict)]))
    bundle = adapt_modular_bundle_to_legacy(story=story, chapter_number=candidate.chapter_number,
        modular_bundle=SimpleNamespace(director_artifact=director, body=candidate.body,
            consistency_findings=[asdict(f) for f in findings], continuity_delta=delta,
            writer_context=context, canon_preflight=preflight, canon_review_snapshot=snapshot))
    bundle.chapter_title = candidate.chapter_title
    # A revised body may realise the same plan differently. The legacy adapter
    # derives its chapter summary from planned scene results; those are not
    # evidence that the revised prose still contains the old events. Rebuild
    # body-derived history from this extraction, never from the saved draft or
    # its director's intended results.
    from packages.story_core.chapter_history import apply_chapter_history
    extracted_sentences = []
    for name in ("entity_additions", "entity_updates", "relationship_changes", "inventory_changes",
                 "task_progressions", "location_movements", "timeline_advances", "foreshadowing_changes"):
        for fact in getattr(delta, name, []):
            sentence = fact.source_sentence.strip()
            if sentence and sentence in candidate.body and sentence not in extracted_sentences:
                extracted_sentences.append(sentence)
    bundle.chapter_summary = {
        **bundle.chapter_summary, "chapter_title": candidate.chapter_title,
        "summary": "正文摘录：" + candidate.body.strip()[:400], "facts": extracted_sentences,
        "unresolved_threads": [], "resolved_threads": [],
        "primary_conflict": {}, "secondary_conflict": {}, "event_beat": {},
    }
    bundle.updated_story = StoryState.model_validate(apply_chapter_history(
        story.model_dump(mode="json"), bundle.chapter_summary))
    bundle.foreshadowing = list(bundle.updated_story.foreshadowing or [])
    payload = store._bundle_to_dict(bundle)
    payload["director_artifact"] = director.model_dump(mode="json")
    if candidate.submission_payload.get("opening_authority"):
        payload["opening_authority"] = deepcopy(candidate.submission_payload["opening_authority"])
    quality = store._merge_candidate_length_review(quality_report=bundle.quality_report,
        bundle=bundle, body=candidate.body)
    payload["quality_report"] = deepcopy(quality)
    with project_update_lock(store.root):
        current = _pending(store, candidate_id, expected)
        if execution.source_fingerprint(store) != source:
            raise ValueError("candidate_review_source_changed")
        current.quality_report = quality
        current.submission_payload = payload
        current.continuity_delta = delta
        current.review_binding = {**current.review_binding, "state": "checked", "source": source}
        current.review_binding["result"] = review_digest(current)
        store.candidate_store.save(current)
        return current


def revise_with_ai(store, candidate_id: str, *, expected: str, guidance: str,
                   writer_runtime=None, consistency_runtime=None) -> CandidateDraft:
    """Save the generated revision before reviewing; failures never lose prose."""
    from packages.story_core.agents import pipeline
    from packages.story_core.agents.contracts import DirectorArtifact
    from packages.story_core.agents.writer import WriterAgent
    from packages.story_core.prompt_templates import prompt_template_scope
    from packages.story_core.prompt_call_log import prompt_call_recording

    if not guidance.strip() or len(guidance) > 10000:
        raise ValueError("candidate_guidance_required")
    with project_update_lock(store.root):
        candidate = _pending(store, candidate_id, expected, refresh_author_inputs=True)
        source = execution.source_fingerprint(store)
        saved_director = candidate.submission_payload.get("director_artifact")
        if not saved_director:
            raise ValueError("candidate_review_planning_missing")
        director = DirectorArtifact.model_validate(saved_director)
        execution.verify_writer_planning(store.root, director)
        context = pipeline._ensure_writer_context(project_root=store.root,
            chapter_number=candidate.chapter_number, director_artifact=director)
        canon = pipeline._ensure_canon_service(store._load_canon_registry(), store.root)
        _, prepared = pipeline._preflight_entities(canon, director)
        context = pipeline._add_prepared_entities_to_context(context, prepared)
        # Keep every existing required context field and the full contract.
        context = context.model_copy(update={"rewrite_guidance": (
            context.rewrite_guidance + "\n请按作者要求修改下面的候选，返回完整正文。\n"
            + guidance + "\n待修改的完整正文：\n" + candidate.body)})
        request = pipeline._build_writer_request(context=context, director_artifact=director)
    with prompt_template_scope(store.prompt_template_object, store.prompt_template_source), prompt_call_recording(store.prompt_call_log()):
        result = WriterAgent(runtime=writer_runtime or pipeline._default_writer_runtime(store.root)).run(request)
    edited = save_edit(store, candidate_id, body=result.body, expected=expected, expected_source=source)
    return recheck(store, edited.candidate_id, expected=candidate_authority(edited),
                   consistency_runtime=consistency_runtime)
