"""Continuation import outline bootstrap.

The continuation import baseline is intentionally small: it writes
the imported chapters, characters, world blueprint, and a single
``pipeline_stage="outline_bootstrapping"`` marker. Everything else
(overall, arcs, future chapters, rolling detail) is generated by
:class:`ContinuationOutlineBootstrapper` *after* the baseline exists
so the workbench never shows a fabricated future plot.

This module owns the contracts that drive that flow:

* :class:`BootstrapPhaseId` / :data:`BOOTSTRAP_PHASES` — the order
  the bootstrapper walks through.
* :class:`BootstrapReadiness` — a pure pydantic snapshot returned by
  :func:`validate_continuation_bootstrap`. The validator is the
  *only* allowed way for callers to decide whether the next chapter
  is write-ready; it must work on disk, not on transient route
  memory, so a page reload always agrees.
* :func:`validate_continuation_bootstrap` — the pure readiness
  validator. It checks concrete files (``outline.json``,
  ``state.json``, ``rolling_outline.json``) and concrete content
  (an arc covering the next chapter, rolling detail for the next
  chapter, a protagonist card, world premise + rules or power
  system, current chapter equals imported chapters). It never
  inspects ``pipeline_stage`` so the validator survives a partial
  bootstrap run.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Literal, Protocol

from pydantic import BaseModel, ConfigDict, Field


BootstrapPhaseId = Literal[
    "source_analysis",
    "outline_foundation",
    "character_roster",
    "world_context",
    "chapter_window",
    "readiness_check",
]


BOOTSTRAP_PHASES: tuple[BootstrapPhaseId, ...] = (
    "source_analysis",
    "outline_foundation",
    "character_roster",
    "world_context",
    "chapter_window",
    "readiness_check",
)


class BootstrapReadiness(BaseModel):
    """A pure snapshot of whether the next chapter is write-ready.

    ``ready`` is the only field a caller should branch on. The
    ``errors`` list is a human-readable list of failing field
    codes; the bootstrapper uses the same codes to surface the
    UI banner. ``next_chapter`` is always the current chapter
    plus one — even when the project is not yet ready — so the
    wizard can render the next-chapter banner before the
    bootstrap completes.
    """

    model_config = ConfigDict(extra="forbid", strict=True)

    ready: bool
    next_chapter: int = Field(ge=1)
    errors: list[str] = Field(default_factory=list)


def _read_json(path: Path) -> Any:
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _coerce_chapter_numbers(value: Any) -> list[int]:
    """Return ``value`` as a list of positive ints.

    Robust against ``None`` / non-list / non-int entries so the
    validator never raises while scanning partially-written project
    files.
    """

    if not isinstance(value, list):
        return []
    numbers: list[int] = []
    for item in value:
        if isinstance(item, bool):
            continue
        if isinstance(item, int) and item > 0:
            numbers.append(item)
    return numbers


def _has_protagonist_card(characters: Any) -> bool:
    if not isinstance(characters, list):
        return False
    for card in characters:
        if not isinstance(card, dict):
            continue
        role = str(card.get("character_tier") or card.get("role") or "").strip().lower()
        if role in {"protagonist", "主角"}:
            return True
    return False


def _world_premise_and_rules(blueprint: Any, state: Any) -> tuple[str, bool, bool]:
    """Return ``(premise, has_rules, has_power_system)``.

    A project passes when ``premise`` is non-empty *and* at least
    one of ``world_rules`` / ``power_system`` is non-empty. The
    ``premise`` is read from the blueprint (the long-lived
    source of truth), with the state's outline as a fallback so a
    project whose blueprint was wiped still surfaces a usable
    premise.
    """

    premise = ""
    has_rules = False
    has_power_system = False
    if isinstance(blueprint, dict):
        premise = str(blueprint.get("premise") or "").strip()
        rules = blueprint.get("world_rules")
        if isinstance(rules, list) and any(str(item or "").strip() for item in rules):
            has_rules = True
        power = blueprint.get("power_system")
        if isinstance(power, list) and any(str(item or "").strip() for item in power):
            has_power_system = True
    if not premise and isinstance(state, dict):
        premise = str(state.get("outline") or state.get("world_summary") or "").strip()
    return premise, has_rules, has_power_system


def _arc_covers(arc: dict[str, Any], chapter_number: int) -> bool:
    if not isinstance(arc, dict):
        return False
    start = arc.get("start_chapter")
    end = arc.get("end_chapter")
    if not isinstance(start, int) or isinstance(start, bool):
        return False
    if not isinstance(end, int) or isinstance(end, bool):
        return False
    return start <= chapter_number <= end


def validate_continuation_bootstrap(project_root: str | Path) -> BootstrapReadiness:
    """Return a pure readiness snapshot for ``project_root``.

    The function never raises; it returns a populated
    :class:`BootstrapReadiness` whose ``errors`` list describes
    what is missing. The check is intentionally file-driven so a
    route reload (or a backfill script) and a re-validated
    in-memory store always agree.

    The error codes form a stable contract; the bootstrap UI keys
    its banners off them.

    * ``import_overall_required`` — ``outline.overall.story`` is blank
    * ``import_arc_required`` — no arc covers the current chapter
    * ``import_future_arc_required`` — no arc covers the next chapter
    * ``import_character_card_required`` — no protagonist card on disk
    * ``import_world_context_required`` — premise / rules / power
      system are all blank
    * ``import_chapter_window_required:{n}`` — no rolling detail for
      chapter ``n`` (next chapter)
    * ``import_current_chapter_mismatch`` — ``state.current_chapter``
      does not equal the maximum committed chapter number
    """

    root = Path(project_root)
    errors: list[str] = []
    next_chapter = 1

    project = _read_json(root / ".webnovel" / "project.json")
    state = _read_json(root / ".webnovel" / "state.json")
    outline = _read_json(root / ".webnovel" / "outline.json")

    current_chapter = 0
    if isinstance(state, dict):
        try:
            current_chapter = int(state.get("current_chapter") or 0)
        except (TypeError, ValueError):
            current_chapter = 0
    if current_chapter <= 0 and isinstance(project, dict):
        try:
            current_chapter = int(project.get("current_chapter") or 0)
        except (TypeError, ValueError):
            current_chapter = 0
    next_chapter = max(1, current_chapter + 1)

    # Overall core fields: the plan rule requires evidence-backed
    # overall. An empty story string is the cheapest signal.
    overall = outline.get("overall") if isinstance(outline, dict) else None
    if not isinstance(overall, dict) or not str(overall.get("story") or "").strip():
        errors.append("import_overall_required")

    # Arc coverage: at least one historical arc must cover the
    # current chapter, and at least one future arc must cover the
    # next chapter.
    arcs = outline.get("arcs") if isinstance(outline, dict) else []
    if not isinstance(arcs, list) or not arcs:
        errors.append("import_arc_required")
        errors.append("import_future_arc_required")
    else:
        if not any(_arc_covers(arc, current_chapter) for arc in arcs):
            errors.append("import_arc_required")
        if not any(_arc_covers(arc, next_chapter) for arc in arcs):
            errors.append("import_future_arc_required")

    # Protagonist card: search both the project's character_profiles
    # and the state's characters list so the test does not depend
    # on which file the import put it in.
    characters: list[Any] = []
    if isinstance(project, dict):
        characters.extend(project.get("character_profiles") or [])
    if isinstance(state, dict):
        characters.extend(state.get("characters") or [])
    if not _has_protagonist_card(characters):
        errors.append("import_character_card_required")

    blueprint = project.get("world_blueprint") if isinstance(project, dict) else None
    premise, has_rules, has_power_system = _world_premise_and_rules(blueprint, state)
    if not premise or not (has_rules or has_power_system):
        errors.append("import_world_context_required")

    # Rolling detail: the next chapter must have a row in
    # ``.story-system/outline-generation/rolling_outline.json``.
    rolling = _read_json(
        root / ".story-system" / "outline-generation" / "rolling_outline.json"
    )
    rolling_chapters = (
        rolling.get("chapters") if isinstance(rolling, dict) else None
    )
    rolling_numbers: set[int] = set()
    if isinstance(rolling_chapters, list):
        rolling_numbers = set(_coerce_chapter_numbers(
            [
                item.get("chapter_number") if isinstance(item, dict) else None
                for item in rolling_chapters
            ]
        ))
    if next_chapter not in rolling_numbers:
        errors.append(f"import_chapter_window_required:{next_chapter}")

    # Current chapter must equal the maximum committed chapter.
    chapters_dir = root / ".story-system" / "chapters"
    committed: list[int] = []
    if chapters_dir.is_dir():
        for chapter_file in chapters_dir.glob("*.json"):
            try:
                payload = json.loads(chapter_file.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if isinstance(payload, dict):
                try:
                    number = int(payload.get("chapter_number") or 0)
                except (TypeError, ValueError):
                    number = 0
                if number > 0:
                    committed.append(number)
    if not committed or max(committed) != current_chapter:
        errors.append("import_current_chapter_mismatch")

    return BootstrapReadiness(
        ready=not errors,
        next_chapter=next_chapter,
        errors=errors,
    )


# ---------------------------------------------------------------------------
# Rolling-compatible chapter window conversion
# ---------------------------------------------------------------------------


def _real_cast_names(character_cards: list[dict[str, Any]]) -> set[str]:
    """Return the set of cast names actually on disk.

    Cast entries the planner hands back may include placeholders
    or roles; the conversion only keeps names that exist as
    concrete character cards so the rolling schema never
    references a person the project does not know.
    """

    names: set[str] = set()
    for card in character_cards:
        if not isinstance(card, dict):
            continue
        name = str(card.get("name") or "").strip()
        if name:
            names.add(name)
    return names


def _coerce_non_blank_str(payload: dict[str, Any], field: str) -> str:
    value = payload.get(field)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"rolling_conversion_field_blank:{field}")
    return value.strip()


def _coerce_scenes(payload: dict[str, Any]) -> list[dict[str, Any]]:
    raw_scenes = payload.get("scene_chain")
    if not isinstance(raw_scenes, list) or len(raw_scenes) < 2:
        raise ValueError("rolling_conversion_scenes_too_few")
    if len(raw_scenes) > 4:
        raise ValueError("rolling_conversion_scenes_too_many")
    scenes: list[dict[str, Any]] = []
    for index, scene in enumerate(raw_scenes):
        if not isinstance(scene, dict):
            raise ValueError(f"rolling_conversion_scene_invalid:{index}")
        location = str(scene.get("location") or "").strip()
        action = str(scene.get("action") or "").strip()
        result = str(scene.get("change") or scene.get("result") or "").strip()
        if not (location and action and result):
            raise ValueError(
                f"rolling_conversion_scene_field_blank:{index}"
            )
        scenes.append(
            {
                "location": location,
                "action": action,
                "result": result,
            }
        )
    return scenes


def _project_chapter(
    payload: dict[str, Any],
    *,
    expected_chapter_number: int,
    real_cast: set[str],
) -> dict[str, Any]:
    """Map one planner-stage chapter row into the rolling schema.

    The conversion is deterministic: ``goal`` becomes
    ``chapter_goal``, ``ending_hook`` becomes ``hook``, and the
    rolling-only fields are passed through unchanged. Cast
    entries are kept only when they match a real character card;
    otherwise the conversion raises so the bootstrapper can fail
    the batch before any disk write.
    """

    chapter_number = payload.get("chapter_number")
    if (
        not isinstance(chapter_number, int)
        or isinstance(chapter_number, bool)
        or chapter_number != expected_chapter_number
    ):
        raise ValueError(
            f"rolling_conversion_chapter_number_mismatch:"
            f"got={chapter_number} expected={expected_chapter_number}"
        )

    raw_cast = payload.get("cast")
    if not isinstance(raw_cast, list) or not raw_cast:
        raise ValueError("rolling_conversion_cast_empty")
    cast: list[dict[str, Any]] = []
    for entry in raw_cast:
        if isinstance(entry, str):
            name = entry.strip()
            role = "supporting"
            character_tier = ""
        elif isinstance(entry, dict):
            name = str(entry.get("name") or "").strip()
            role = str(entry.get("role") or "").strip() or "supporting"
            character_tier = str(entry.get("character_tier") or "").strip()
        else:
            raise ValueError("rolling_conversion_cast_entry_invalid")
        if not name:
            raise ValueError("rolling_conversion_cast_entry_blank")
        if name not in real_cast:
            raise ValueError(f"rolling_conversion_cast_unknown:{name}")
        cast.append(
            {
                "name": name,
                "role": role,
                "character_tier": character_tier,
            }
        )

    chapter_goal = _coerce_non_blank_str(payload, "goal")
    core_conflict = _coerce_non_blank_str(payload, "core_conflict")
    gain = _coerce_non_blank_str(payload, "gain")
    cost = _coerce_non_blank_str(payload, "cost")
    hook = _coerce_non_blank_str(payload, "ending_hook")
    state_delta = _coerce_non_blank_str(payload, "state_delta_summary")
    foreshadowing = payload.get("foreshadowing")
    if not isinstance(foreshadowing, list):
        raise ValueError("rolling_conversion_foreshadowing_invalid")
    clean_foreshadowing = [
        str(item).strip() for item in foreshadowing if str(item or "").strip()
    ]
    scenes = _coerce_scenes(payload)

    return {
        "chapter_number": chapter_number,
        "title": str(payload.get("title") or "").strip(),
        "chapter_goal": chapter_goal,
        "core_conflict": core_conflict,
        "cast": cast,
        "scenes": scenes,
        "gain": gain,
        "cost": cost,
        "foreshadowing": clean_foreshadowing,
        "hook": hook,
        "state_delta": state_delta,
    }


def rolling_batch_from_generated_window(
    *,
    chapters: list[dict[str, Any]],
    character_cards: list[dict[str, Any]],
    volume_range: tuple[int, int],
) -> list[dict[str, Any]]:
    """Project a planner-stage window into rolling-schema rows.

    The function is pure: it never touches the disk. The caller
    is responsible for handing the returned batch to
    :class:`RollingOutlineStore.apply_rolling_batch`, which runs
    the same ``validate_rolling_batch`` contract.

    Plan rules enforced here:

    * blank ``gain`` / ``cost`` / ``hook`` / ``state_delta``
      raise ``ValueError`` before any row is built;
    * fewer than 2 scenes or more than 4 raise ``ValueError``;
    * unknown cast names raise ``ValueError``;
    * chapter numbers must equal the expected slot in order;
    * a chapter that fails any check fails the whole batch.
    """

    if not chapters:
        raise ValueError("rolling_conversion_empty_batch")
    real_cast = _real_cast_names(character_cards)
    start, end = volume_range
    rows: list[dict[str, Any]] = []
    failures: list[str] = []
    for index, payload in enumerate(chapters):
        expected_number = start + index
        if expected_number > end:
            failures.append(
                f"rolling_conversion_volume_exceeded:expected={expected_number} end={end}"
            )
            continue
        if not isinstance(payload, dict):
            failures.append(
                f"rolling_conversion_chapter_not_dict:index={index}"
            )
            continue
        try:
            rows.append(
                _project_chapter(
                    payload,
                    expected_chapter_number=expected_number,
                    real_cast=real_cast,
                )
            )
        except ValueError as exc:
            failures.append(str(exc))
    if failures:
        joined = "; ".join(failures)
        raise ValueError(f"rolling_batch_conversion_failed:{joined}")
    return rows


class RollingWindowGenerator(Protocol):
    """Narrow generator interface for legacy-approved projects.

    When a project already has approved overall / arcs /
    characters, the bootstrapper must NOT call the full planning
    generator. It calls one of these generators with only the
    rolling-relevant context (active arc, recent summaries,
    character cards, world rules, open foreshadowing, requested
    chapter numbers) so the rolling window can be filled without
    rewriting the three-level outline.
    """

    def generate(
        self,
        *,
        context: dict[str, Any],
        chapter_numbers: list[int],
        volume_range: tuple[int, int],
        character_cards: list[dict[str, Any]],
    ) -> list[dict[str, Any]]: ...


class LLMRollingWindowGenerator:
    """Production rolling-only generator.

    The generator makes one planner-stage JSON call for the
    complete window, validates the returned batch, and returns the
    rolling rows. It has no filesystem access: the caller is the
    bootstrapper, which owns disk writes.
    """

    def __init__(self, *, gateway: Any | None = None) -> None:
        # Lazily import the model gateway so the bootstrap module
        # stays importable in unit tests that never touch a model
        # runtime.
        if gateway is None:
            from packages.story_core.model_gateway import (
                ModelRequest,
                RuntimeModelGateway,
            )
            from packages.story_core.runtime_config import resolve_stage_runtime

            self._gateway = RuntimeModelGateway(
                runtime_resolver=resolve_stage_runtime,
            )
            self._ModelRequest = ModelRequest
        else:
            self._gateway = gateway
            from packages.story_core.model_gateway import ModelRequest

            self._ModelRequest = ModelRequest

    def generate(
        self,
        *,
        context: dict[str, Any],
        chapter_numbers: list[int],
        volume_range: tuple[int, int],
        character_cards: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        from packages.story_core.agent_base import parse_json_message_content
        from packages.story_core.outline_planning_generation import (
            GeneratedChapterWindow,
        )
        from packages.story_core.outline_rolling import validate_rolling_batch

        if not chapter_numbers:
            raise ValueError("rolling_window_no_chapter_numbers")
        request_payload = {
            "context": context,
            "chapter_numbers": list(chapter_numbers),
            "volume_range": list(volume_range),
            "character_cards": list(character_cards),
        }
        response = self._gateway.complete_stage(
            "planner",
            self._ModelRequest(
                prompt="",
                messages=(
                    {
                        "role": "system",
                        "content": (
                            "Generate the requested rolling chapter window. "
                            "Return JSON with the single root field chapters. "
                            "Each chapter must include core_conflict, gain, cost, "
                            "foreshadowing, state_delta_summary, and a scene_chain "
                            "of 2 to 4 scenes. Cast names must come from "
                            "prompt_context.character_cards."
                        ),
                    },
                    {
                        "role": "user",
                        "content": json.dumps(
                            request_payload, ensure_ascii=False
                        ),
                    },
                ),
                provider="",
                model="",
                operation="rolling_window",
                temperature=None,
                max_tokens=None,
                json_mode=True,
            ),
        )
        if not response.ok:
            raise ValueError(response.error or "rolling_window_model_call_failed")
        data = parse_json_message_content({"choices": [{"message": {"content": response.text}}]})
        if data is None:
            raise ValueError("rolling_window_invalid_json")
        window = GeneratedChapterWindow.model_validate(data)
        batch = rolling_batch_from_generated_window(
            chapters=[row.model_dump(mode="python") for row in window.chapters],
            character_cards=list(character_cards),
            volume_range=tuple(volume_range),
        )
        validate_rolling_batch(
            batch,
            expected_chapter_numbers=list(chapter_numbers),
            volume_range=tuple(volume_range),
        )
        return batch


__all__ = [
    "BOOTSTRAP_PHASES",
    "BootstrapPhaseId",
    "BootstrapReadiness",
    "LLMRollingWindowGenerator",
    "RollingWindowGenerator",
    "rolling_batch_from_generated_window",
    "validate_continuation_bootstrap",
]
