"""Continuation import outline bootstrap.

The continuation import baseline is intentionally small: it writes
the imported chapters, characters, world blueprint, and a single
``pipeline_stage="outline_bootstrapping"`` marker. Everything else
(overall, arcs, future chapters, rolling detail) is generated by
:class:`ContinuationOutlineBootstrapper` *after* the baseline exists
so the workbench never shows a fabricated future plot.

This module owns the contracts that drive that flow:

* :class:`BootstrapPhaseId` / :data:`BOOTSTRAP_PHASES` — the order
  the bootstrapper walks through.
* :class:`BootstrapReadiness` — a pure pydantic snapshot returned by
  :func:`validate_continuation_bootstrap`. The validator is the
  *only* allowed way for callers to decide whether the next chapter
  is write-ready; it must work on disk, not on transient route
  memory, so a page reload always agrees.
* :func:`validate_continuation_bootstrap` — the pure readiness
  validator. It checks concrete files (``outline.json``,
  ``state.json``, ``rolling_outline.json``) and concrete content
  (an arc covering the next chapter, rolling detail for the next
  chapter, a protagonist card, world premise + rules or power
  system, current chapter equals imported chapters). It never
  inspects ``pipeline_stage`` so the validator survives a partial
  bootstrap run.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal, Protocol

from pydantic import BaseModel, ConfigDict, Field


BootstrapPhaseId = Literal[
    "source_analysis",
    "outline_foundation",
    "character_roster",
    "world_context",
    "chapter_window",
    "readiness_check",
]


BOOTSTRAP_PHASES: tuple[BootstrapPhaseId, ...] = (
    "source_analysis",
    "outline_foundation",
    "character_roster",
    "world_context",
    "chapter_window",
    "readiness_check",
)


class BootstrapReadiness(BaseModel):
    """A pure snapshot of whether the next chapter is write-ready.

    ``ready`` is the only field a caller should branch on. The
    ``errors`` list is a human-readable list of failing field
    codes; the bootstrapper uses the same codes to surface the
    UI banner. ``next_chapter`` is always the current chapter
    plus one — even when the project is not yet ready — so the
    wizard can render the next-chapter banner before the
    bootstrap completes.
    """

    model_config = ConfigDict(extra="forbid", strict=True)

    ready: bool
    next_chapter: int = Field(ge=1)
    errors: list[str] = Field(default_factory=list)


def _read_json(path: Path) -> Any:
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _coerce_chapter_numbers(value: Any) -> list[int]:
    """Return ``value`` as a list of positive ints.

    Robust against ``None`` / non-list / non-int entries so the
    validator never raises while scanning partially-written project
    files.
    """

    if not isinstance(value, list):
        return []
    numbers: list[int] = []
    for item in value:
        if isinstance(item, bool):
            continue
        if isinstance(item, int) and item > 0:
            numbers.append(item)
    return numbers


def _has_protagonist_card(characters: Any) -> bool:
    if not isinstance(characters, list):
        return False
    for card in characters:
        if not isinstance(card, dict):
            continue
        role = str(card.get("character_tier") or card.get("role") or "").strip().lower()
        if role in {"protagonist", "主角"}:
            return True
    return False


def _world_premise_and_rules(blueprint: Any, state: Any) -> tuple[str, bool, bool]:
    """Return ``(premise, has_rules, has_power_system)``.

    A project passes when ``premise`` is non-empty *and* at least
    one of ``world_rules`` / ``power_system`` is non-empty. The
    ``premise`` is read from the blueprint (the long-lived
    source of truth), with the state's outline as a fallback so a
    project whose blueprint was wiped still surfaces a usable
    premise.
    """

    premise = ""
    has_rules = False
    has_power_system = False
    if isinstance(blueprint, dict):
        premise = str(blueprint.get("premise") or "").strip()
        rules = blueprint.get("world_rules")
        if isinstance(rules, list) and any(str(item or "").strip() for item in rules):
            has_rules = True
        power = blueprint.get("power_system")
        if isinstance(power, list) and any(str(item or "").strip() for item in power):
            has_power_system = True
    if not premise and isinstance(state, dict):
        premise = str(state.get("outline") or state.get("world_summary") or "").strip()
    return premise, has_rules, has_power_system


def _arc_covers(arc: dict[str, Any], chapter_number: int) -> bool:
    if not isinstance(arc, dict):
        return False
    start = arc.get("start_chapter")
    end = arc.get("end_chapter")
    if not isinstance(start, int) or isinstance(start, bool):
        return False
    if not isinstance(end, int) or isinstance(end, bool):
        return False
    return start <= chapter_number <= end


def validate_continuation_bootstrap(project_root: str | Path) -> BootstrapReadiness:
    """Return a pure readiness snapshot for ``project_root``.

    The function never raises; it returns a populated
    :class:`BootstrapReadiness` whose ``errors`` list describes
    what is missing. The check is intentionally file-driven so a
    route reload (or a backfill script) and a re-validated
    in-memory store always agree.

    The error codes form a stable contract; the bootstrap UI keys
    its banners off them.

    * ``import_overall_required`` — ``outline.overall.story`` is blank
    * ``import_arc_required`` — no arc covers the current chapter
    * ``import_future_arc_required`` — no arc covers the next chapter
    * ``import_character_card_required`` — no protagonist card on disk
    * ``import_world_context_required`` — premise / rules / power
      system are all blank
    * ``import_chapter_window_required:{n}`` — no rolling detail for
      chapter ``n`` (next chapter)
    * ``import_current_chapter_mismatch`` — ``state.current_chapter``
      does not equal the maximum committed chapter number
    """

    root = Path(project_root)
    errors: list[str] = []
    next_chapter = 1

    project = _read_json(root / ".webnovel" / "project.json")
    state = _read_json(root / ".webnovel" / "state.json")
    outline = _read_json(root / ".webnovel" / "outline.json")

    current_chapter = 0
    if isinstance(state, dict):
        try:
            current_chapter = int(state.get("current_chapter") or 0)
        except (TypeError, ValueError):
            current_chapter = 0
    if current_chapter <= 0 and isinstance(project, dict):
        try:
            current_chapter = int(project.get("current_chapter") or 0)
        except (TypeError, ValueError):
            current_chapter = 0
    next_chapter = max(1, current_chapter + 1)

    # Overall core fields: the plan rule requires evidence-backed
    # overall. An empty story string is the cheapest signal.
    overall = outline.get("overall") if isinstance(outline, dict) else None
    if not isinstance(overall, dict) or not str(overall.get("story") or "").strip():
        errors.append("import_overall_required")

    # Arc coverage: at least one historical arc must cover the
    # current chapter, and at least one future arc must cover the
    # next chapter.
    arcs = outline.get("arcs") if isinstance(outline, dict) else []
    if not isinstance(arcs, list) or not arcs:
        errors.append("import_arc_required")
        errors.append("import_future_arc_required")
    else:
        if not any(_arc_covers(arc, current_chapter) for arc in arcs):
            errors.append("import_arc_required")
        if not any(_arc_covers(arc, next_chapter) for arc in arcs):
            errors.append("import_future_arc_required")

    # Protagonist card: search both the project's character_profiles
    # and the state's characters list so the test does not depend
    # on which file the import put it in.
    characters: list[Any] = []
    if isinstance(project, dict):
        characters.extend(project.get("character_profiles") or [])
    if isinstance(state, dict):
        characters.extend(state.get("characters") or [])
    if not _has_protagonist_card(characters):
        errors.append("import_character_card_required")

    blueprint = project.get("world_blueprint") if isinstance(project, dict) else None
    premise, has_rules, has_power_system = _world_premise_and_rules(blueprint, state)
    if not premise or not (has_rules or has_power_system):
        errors.append("import_world_context_required")

    # Rolling detail: the next chapter must have a row in
    # ``.story-system/outline-generation/rolling_outline.json``.
    rolling = _read_json(
        root / ".story-system" / "outline-generation" / "rolling_outline.json"
    )
    rolling_chapters = (
        rolling.get("chapters") if isinstance(rolling, dict) else None
    )
    rolling_numbers: set[int] = set()
    if isinstance(rolling_chapters, list):
        rolling_numbers = set(_coerce_chapter_numbers(
            [
                item.get("chapter_number") if isinstance(item, dict) else None
                for item in rolling_chapters
            ]
        ))
    if next_chapter not in rolling_numbers:
        errors.append(f"import_chapter_window_required:{next_chapter}")

    # Current chapter must equal the maximum committed chapter.
    chapters_dir = root / ".story-system" / "chapters"
    committed: list[int] = []
    if chapters_dir.is_dir():
        for chapter_file in chapters_dir.glob("*.json"):
            try:
                payload = json.loads(chapter_file.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if isinstance(payload, dict):
                try:
                    number = int(payload.get("chapter_number") or 0)
                except (TypeError, ValueError):
                    number = 0
                if number > 0:
                    committed.append(number)
    if not committed or max(committed) != current_chapter:
        errors.append("import_current_chapter_mismatch")

    return BootstrapReadiness(
        ready=not errors,
        next_chapter=next_chapter,
        errors=errors,
    )


# ---------------------------------------------------------------------------
# Rolling-compatible chapter window conversion
# ---------------------------------------------------------------------------


def _real_cast_names(character_cards: list[dict[str, Any]]) -> set[str]:
    """Return the set of cast names actually on disk.

    Cast entries the planner hands back may include placeholders
    or roles; the conversion only keeps names that exist as
    concrete character cards so the rolling schema never
    references a person the project does not know.
    """

    names: set[str] = set()
    for card in character_cards:
        if not isinstance(card, dict):
            continue
        name = str(card.get("name") or "").strip()
        if name:
            names.add(name)
    return names


def _coerce_non_blank_str(payload: dict[str, Any], field: str) -> str:
    value = payload.get(field)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"rolling_conversion_field_blank:{field}")
    return value.strip()


def _coerce_scenes(payload: dict[str, Any]) -> list[dict[str, Any]]:
    raw_scenes = payload.get("scene_chain")
    if not isinstance(raw_scenes, list) or len(raw_scenes) < 2:
        raise ValueError("rolling_conversion_scenes_too_few")
    if len(raw_scenes) > 4:
        raise ValueError("rolling_conversion_scenes_too_many")
    scenes: list[dict[str, Any]] = []
    for index, scene in enumerate(raw_scenes):
        if not isinstance(scene, dict):
            raise ValueError(f"rolling_conversion_scene_invalid:{index}")
        location = str(scene.get("location") or "").strip()
        action = str(scene.get("action") or "").strip()
        result = str(scene.get("change") or scene.get("result") or "").strip()
        if not (location and action and result):
            raise ValueError(
                f"rolling_conversion_scene_field_blank:{index}"
            )
        scenes.append(
            {
                "location": location,
                "action": action,
                "result": result,
            }
        )
    return scenes


def _project_chapter(
    payload: dict[str, Any],
    *,
    expected_chapter_number: int,
    real_cast: set[str],
) -> dict[str, Any]:
    """Map one planner-stage chapter row into the rolling schema.

    The conversion is deterministic: ``goal`` becomes
    ``chapter_goal``, ``ending_hook`` becomes ``hook``, and the
    rolling-only fields are passed through unchanged. Cast
    entries are kept only when they match a real character card;
    otherwise the conversion raises so the bootstrapper can fail
    the batch before any disk write.
    """

    chapter_number = payload.get("chapter_number")
    if (
        not isinstance(chapter_number, int)
        or isinstance(chapter_number, bool)
        or chapter_number != expected_chapter_number
    ):
        raise ValueError(
            f"rolling_conversion_chapter_number_mismatch:"
            f"got={chapter_number} expected={expected_chapter_number}"
        )

    raw_cast = payload.get("cast")
    if not isinstance(raw_cast, list) or not raw_cast:
        raise ValueError("rolling_conversion_cast_empty")
    cast: list[dict[str, Any]] = []
    for entry in raw_cast:
        if isinstance(entry, str):
            name = entry.strip()
            role = "supporting"
            character_tier = ""
        elif isinstance(entry, dict):
            name = str(entry.get("name") or "").strip()
            role = str(entry.get("role") or "").strip() or "supporting"
            character_tier = str(entry.get("character_tier") or "").strip()
        else:
            raise ValueError("rolling_conversion_cast_entry_invalid")
        if not name:
            raise ValueError("rolling_conversion_cast_entry_blank")
        if name not in real_cast:
            raise ValueError(f"rolling_conversion_cast_unknown:{name}")
        cast.append(
            {
                "name": name,
                "role": role,
                "character_tier": character_tier,
            }
        )

    chapter_goal = _coerce_non_blank_str(payload, "goal")
    core_conflict = _coerce_non_blank_str(payload, "core_conflict")
    gain = _coerce_non_blank_str(payload, "gain")
    cost = _coerce_non_blank_str(payload, "cost")
    hook = _coerce_non_blank_str(payload, "ending_hook")
    state_delta = _coerce_non_blank_str(payload, "state_delta_summary")
    foreshadowing = payload.get("foreshadowing")
    if not isinstance(foreshadowing, list):
        raise ValueError("rolling_conversion_foreshadowing_invalid")
    clean_foreshadowing = [
        str(item).strip() for item in foreshadowing if str(item or "").strip()
    ]
    scenes = _coerce_scenes(payload)

    return {
        "chapter_number": chapter_number,
        "title": str(payload.get("title") or "").strip(),
        "chapter_goal": chapter_goal,
        "core_conflict": core_conflict,
        "cast": cast,
        "scenes": scenes,
        "gain": gain,
        "cost": cost,
        "foreshadowing": clean_foreshadowing,
        "hook": hook,
        "state_delta": state_delta,
    }


def rolling_batch_from_generated_window(
    *,
    chapters: list[dict[str, Any]],
    character_cards: list[dict[str, Any]],
    volume_range: tuple[int, int],
) -> list[dict[str, Any]]:
    """Project a planner-stage window into rolling-schema rows.

    The function is pure: it never touches the disk. The caller
    is responsible for handing the returned batch to
    :class:`RollingOutlineStore.apply_rolling_batch`, which runs
    the same ``validate_rolling_batch`` contract.

    Plan rules enforced here:

    * blank ``gain`` / ``cost`` / ``hook`` / ``state_delta``
      raise ``ValueError`` before any row is built;
    * fewer than 2 scenes or more than 4 raise ``ValueError``;
    * unknown cast names raise ``ValueError``;
    * chapter numbers must equal the expected slot in order;
    * a chapter that fails any check fails the whole batch.
    """

    if not chapters:
        raise ValueError("rolling_conversion_empty_batch")
    real_cast = _real_cast_names(character_cards)
    start, end = volume_range
    rows: list[dict[str, Any]] = []
    failures: list[str] = []
    for index, payload in enumerate(chapters):
        expected_number = start + index
        if expected_number > end:
            failures.append(
                f"rolling_conversion_volume_exceeded:expected={expected_number} end={end}"
            )
            continue
        if not isinstance(payload, dict):
            failures.append(
                f"rolling_conversion_chapter_not_dict:index={index}"
            )
            continue
        try:
            rows.append(
                _project_chapter(
                    payload,
                    expected_chapter_number=expected_number,
                    real_cast=real_cast,
                )
            )
        except ValueError as exc:
            failures.append(str(exc))
    if failures:
        joined = "; ".join(failures)
        raise ValueError(f"rolling_batch_conversion_failed:{joined}")
    return rows


class RollingWindowGenerator(Protocol):
    """Narrow generator interface for legacy-approved projects.

    When a project already has approved overall / arcs /
    characters, the bootstrapper must NOT call the full planning
    generator. It calls one of these generators with only the
    rolling-relevant context (active arc, recent summaries,
    character cards, world rules, open foreshadowing, requested
    chapter numbers) so the rolling window can be filled without
    rewriting the three-level outline.
    """

    def generate(
        self,
        *,
        context: dict[str, Any],
        chapter_numbers: list[int],
        volume_range: tuple[int, int],
        character_cards: list[dict[str, Any]],
    ) -> list[dict[str, Any]]: ...


class LLMRollingWindowGenerator:
    """Production rolling-only generator.

    The generator makes one planner-stage JSON call for the
    complete window, validates the returned batch, and returns the
    rolling rows. It has no filesystem access: the caller is the
    bootstrapper, which owns disk writes.
    """

    def __init__(self, *, gateway: Any | None = None) -> None:
        # Lazily import the model gateway so the bootstrap module
        # stays importable in unit tests that never touch a model
        # runtime.
        if gateway is None:
            from packages.story_core.model_gateway import (
                ModelRequest,
                RuntimeModelGateway,
            )
            from packages.story_core.runtime_config import resolve_stage_runtime

            self._gateway = RuntimeModelGateway(
                runtime_resolver=resolve_stage_runtime,
            )
            self._ModelRequest = ModelRequest
        else:
            self._gateway = gateway
            from packages.story_core.model_gateway import ModelRequest

            self._ModelRequest = ModelRequest

    def generate(
        self,
        *,
        context: dict[str, Any],
        chapter_numbers: list[int],
        volume_range: tuple[int, int],
        character_cards: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        from packages.story_core.agent_base import parse_json_message_content
        from packages.story_core.outline_planning_generation import (
            GeneratedChapterWindow,
        )
        from packages.story_core.outline_rolling import validate_rolling_batch

        if not chapter_numbers:
            raise ValueError("rolling_window_no_chapter_numbers")
        request_payload = {
            "context": context,
            "chapter_numbers": list(chapter_numbers),
            "volume_range": list(volume_range),
            "character_cards": list(character_cards),
        }
        response = self._gateway.complete_stage(
            "planner",
            self._ModelRequest(
                prompt="",
                messages=(
                    {
                        "role": "system",
                        "content": (
                            "Generate the requested rolling chapter window. "
                            "Return JSON with the single root field chapters. "
                            "Each chapter must include core_conflict, gain, cost, "
                            "foreshadowing, state_delta_summary, and a scene_chain "
                            "of 2 to 4 scenes. Cast names must come from "
                            "prompt_context.character_cards."
                        ),
                    },
                    {
                        "role": "user",
                        "content": json.dumps(
                            request_payload, ensure_ascii=False
                        ),
                    },
                ),
                provider="",
                model="",
                operation="rolling_window",
                temperature=None,
                max_tokens=None,
                json_mode=True,
            ),
        )
        if not response.ok:
            raise ValueError(response.error or "rolling_window_model_call_failed")
        data = parse_json_message_content({"choices": [{"message": {"content": response.text}}]})
        if data is None:
            raise ValueError("rolling_window_invalid_json")
        window = GeneratedChapterWindow.model_validate(data)
        batch = rolling_batch_from_generated_window(
            chapters=[row.model_dump(mode="python") for row in window.chapters],
            character_cards=list(character_cards),
            volume_range=tuple(volume_range),
        )
        validate_rolling_batch(
            batch,
            expected_chapter_numbers=list(chapter_numbers),
            volume_range=tuple(volume_range),
        )
        return batch


__all__ = [
    "BOOTSTRAP_PHASES",
    "BootstrapPhaseId",
    "BootstrapReadiness",
    "ContinuationOutlineBootstrapper",
    "LLMRollingWindowGenerator",
    "RollingWindowGenerator",
    "rolling_batch_from_generated_window",
    "validate_continuation_bootstrap",
]


# ---------------------------------------------------------------------------
# Resumable bootstrap orchestrator
# ---------------------------------------------------------------------------


_BOOTSTRAP_CHECKPOINT_SCHEMA = "continuation-bootstrap/v1"
_BOOTSTRAP_CHECKPOINT_DIRNAME = "continuation-bootstrap"
_BOOTSTRAP_CHECKPOINT_FILENAME = "checkpoint.json"
_BOOTSTRAP_DEFAULT_WINDOW = 5


class _BootstrapPhaseRecord(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)

    id: "BootstrapPhaseId"
    status: Literal["pending", "running", "completed", "failed", "adopted"]
    artifact: dict[str, Any] = Field(default_factory=dict)
    error: str = ""


class _BootstrapCheckpoint(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)

    schema_version: Literal["continuation-bootstrap/v1"] = (
        _BOOTSTRAP_CHECKPOINT_SCHEMA
    )
    input_fingerprint: str = ""
    status: Literal["running", "ready", "failed"] = "running"
    phases: list[_BootstrapPhaseRecord] = Field(default_factory=list)


def _now_isoformat() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")


def _checkpoint_path(root: Path) -> Path:
    return (
        root
        / ".story-system"
        / _BOOTSTRAP_CHECKPOINT_DIRNAME
        / _BOOTSTRAP_CHECKPOINT_FILENAME
    )


def _read_json(path: Path) -> Any:
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _write_json_atomic(target: Path, payload: Any) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(target.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
        handle.flush()
    tmp.replace(target)


def _phase_index(records: list[_BootstrapPhaseRecord], phase: str) -> int:
    for index, record in enumerate(records):
        if record.id == phase:
            return index
    return -1


def _empty_phases() -> list[_BootstrapPhaseRecord]:
    return [
        _BootstrapPhaseRecord(id=phase, status="pending")
        for phase in BOOTSTRAP_PHASES
    ]


class ContinuationOutlineBootstrapper:
    """Resumable bootstrap orchestrator.

    The bootstrapper walks through the six
    :data:`BOOTSTRAP_PHASES` for the imported project:

    1. ``source_analysis`` — read the persisted continuation
       analysis (the baseline is already on disk).
    2. ``outline_foundation`` — when the three-level outline
       is missing or stale, call the planning generator with
       ``mode="regenerate", persist_chapter_window=False`` so
       the legacy outline keeps only overall/arcs/characters
       plus the committed historical chapter rows.
    3. ``character_roster`` — adopt the planning generator's
       characters when produced, otherwise keep the imported
       ones.
    4. ``world_context`` — normalize the confirmed world claims
       into the project blueprint (no second model call).
    5. ``chapter_window`` — call the rolling-only generator
       for exactly the next five chapters, validate the batch,
       and write it via :class:`RollingOutlineStore`.
    6. ``readiness_check`` — run
       :func:`validate_continuation_bootstrap` and, on success,
       set ``pipeline_stage="world_ready"``.

    Each phase writes a checkpoint row to
    ``.story-system/continuation-bootstrap/checkpoint.json``.
    The checkpoint also carries an ``input_fingerprint``: when
    the analysis, genre, continuation point, source
    fingerprint, and guidance all match a previous run, the
    bootstrapper reuses the completed phase rows and does not
    call a model again.

    The bootstrapper never overwrites committed chapter rows
    or rolling chapters the user marked ``source="manual"``.
    """

    def __init__(
        self,
        *,
        project_root: str | Path,
        planning_generator: Any,
        rolling_generator: Any,
        window: int = _BOOTSTRAP_DEFAULT_WINDOW,
    ) -> None:
        self._root = Path(project_root)
        self._planning_generator = planning_generator
        self._rolling_generator = rolling_generator
        self._window = max(1, int(window))

    # -- public API -------------------------------------------------------

    def read_checkpoint(self) -> dict[str, Any]:
        """Return the current bootstrap checkpoint payload.

        Used by the API status endpoint so a route reload never
        loses progress: the JSON is the single source of truth.
        """
        path = _checkpoint_path(self._root)
        payload = _read_json(path)
        if not isinstance(payload, dict):
            return {
                "schema_version": _BOOTSTRAP_CHECKPOINT_SCHEMA,
                "input_fingerprint": "",
                "status": "running",
                "phases": [
                    {"id": phase, "status": "pending", "artifact": {}, "error": ""}
                    for phase in BOOTSTRAP_PHASES
                ],
            }
        return payload

    def run(self) -> BootstrapReadiness:
        """Run the bootstrap until ready or until a phase fails.

        The function is idempotent: a re-run with the same
        input fingerprint reuses the completed phases and
        skips the model calls. A re-run with a different
        fingerprint invalidates the affected phase and starts
        from there.
        """
        analysis = self._read_continuation_analysis()
        fingerprint = self._compute_fingerprint(analysis)
        checkpoint = self._load_checkpoint(fingerprint)
        self._adopt_existing_layers(checkpoint)

        next_chapter = self._current_chapter() + 1
        if next_chapter < 1:
            next_chapter = 1
        next_window = list(
            range(next_chapter, next_chapter + self._window)
        )

        try:
            self._ensure_source_analysis(checkpoint, analysis)
            self._ensure_world_context(checkpoint)
            self._ensure_outline_and_characters(checkpoint)
            self._ensure_chapter_window(checkpoint, next_window)
            self._ensure_readiness(checkpoint)
        except _BootstrapFailure as failure:
            self._mark_failed(checkpoint, failure.phase, failure.error)
            self._persist_checkpoint(checkpoint, status="failed", fingerprint=fingerprint)
            return validate_continuation_bootstrap(self._root)

        self._persist_checkpoint(checkpoint, status="ready", fingerprint=fingerprint)
        self._mark_world_ready()
        return validate_continuation_bootstrap(self._root)

    # -- checkpoint helpers -----------------------------------------------

    def _load_checkpoint(self, fingerprint: str) -> _BootstrapCheckpoint:
        payload = _read_json(_checkpoint_path(self._root))
        if isinstance(payload, dict) and payload.get("input_fingerprint") == fingerprint:
            try:
                checkpoint = _BootstrapCheckpoint.model_validate(payload)
            except ValueError:
                checkpoint = _BootstrapCheckpoint(
                    input_fingerprint=fingerprint,
                    status="running",
                    phases=_empty_phases(),
                )
            else:
                # The fingerprint matches; reconcile any phases
                # that are still in the ``pending`` state so a
                # brand-new ``pending`` list does not lose
                # the data the previous run already produced.
                existing_ids = {record.id for record in checkpoint.phases}
                for phase_id in BOOTSTRAP_PHASES:
                    if phase_id not in existing_ids:
                        checkpoint.phases.append(
                            _BootstrapPhaseRecord(id=phase_id, status="pending")
                        )
                return checkpoint
        return _BootstrapCheckpoint(
            input_fingerprint=fingerprint,
            status="running",
            phases=_empty_phases(),
        )

    def _persist_checkpoint(
        self,
        checkpoint: _BootstrapCheckpoint,
        *,
        status: str,
        fingerprint: str,
    ) -> None:
        checkpoint.status = status  # type: ignore[assignment]
        checkpoint.input_fingerprint = fingerprint
        _write_json_atomic(_checkpoint_path(self._root), checkpoint.model_dump(mode="json"))

    def _mark_phase(
        self,
        checkpoint: _BootstrapCheckpoint,
        phase: str,
        status: str,
        artifact: dict[str, Any] | None = None,
        error: str = "",
    ) -> None:
        index = _phase_index(checkpoint.phases, phase)
        record = _BootstrapPhaseRecord(
            id=phase,  # type: ignore[arg-type]
            status=status,  # type: ignore[arg-type]
            artifact=artifact or {},
            error=error,
        )
        if index >= 0:
            checkpoint.phases[index] = record
        else:
            checkpoint.phases.append(record)

    def _mark_failed(
        self,
        checkpoint: _BootstrapCheckpoint,
        phase: str,
        error: str,
    ) -> None:
        index = _phase_index(checkpoint.phases, phase)
        if index >= 0:
            checkpoint.phases[index].status = "failed"
            checkpoint.phases[index].error = error
        else:
            checkpoint.phases.append(
                _BootstrapPhaseRecord(
                    id=phase,  # type: ignore[arg-type]
                    status="failed",
                    error=error,
                )
            )

    def _phase_status(
        self,
        checkpoint: _BootstrapCheckpoint,
        phase: str,
    ) -> str:
        index = _phase_index(checkpoint.phases, phase)
        if index < 0:
            return "pending"
        return checkpoint.phases[index].status

    # -- phase implementations --------------------------------------------

    def _ensure_source_analysis(
        self,
        checkpoint: _BootstrapCheckpoint,
        analysis: dict[str, Any],
    ) -> None:
        if self._phase_status(checkpoint, "source_analysis") in {
            "completed",
            "adopted",
        }:
            return
        if not analysis:
            raise _BootstrapFailure(
                "source_analysis",
                "continuation_analysis_not_confirmed",
            )
        self._mark_phase(
            checkpoint,
            "source_analysis",
            "completed",
            artifact={"fingerprint": self._compute_fingerprint(analysis)},
        )

    def _ensure_world_context(self, checkpoint: _BootstrapCheckpoint) -> None:
        if self._phase_status(checkpoint, "world_context") in {
            "completed",
            "adopted",
        }:
            return
        # No second model call: the world blueprint was
        # produced during the import baseline; the bootstrapper
        # only needs to mark the phase as adopted.
        self._mark_phase(
            checkpoint,
            "world_context",
            "adopted",
            artifact={"source": "imported_baseline"},
        )

    def _ensure_outline_and_characters(
        self,
        checkpoint: _BootstrapCheckpoint,
    ) -> None:
        # Adopt foundation / character phases when the
        # imported baseline already has valid rows; otherwise
        # call the planning generator with
        # ``persist_chapter_window=False`` so the legacy outline
        # never grows a fabricated future plot.
        if self._phase_status(checkpoint, "outline_foundation") in {
            "completed",
            "adopted",
        } and self._phase_status(checkpoint, "character_roster") in {
            "completed",
            "adopted",
        }:
            return

        if self._outline_layers_already_valid():
            self._mark_phase(
                checkpoint,
                "outline_foundation",
                "adopted",
                artifact={"source": "imported_baseline"},
            )
            self._mark_phase(
                checkpoint,
                "character_roster",
                "adopted",
                artifact={"source": "imported_baseline"},
            )
            return

        snapshot = self._call_planning_generator()
        foundation = (
            snapshot.get("outline_foundation")
            if isinstance(snapshot, dict)
            else None
        )
        roster = (
            snapshot.get("character_roster")
            if isinstance(snapshot, dict)
            else None
        )
        if not isinstance(foundation, dict) or not isinstance(roster, list):
            raise _BootstrapFailure(
                "outline_foundation",
                "outline_planning_generation_failed",
            )
        self._mark_phase(
            checkpoint,
            "outline_foundation",
            "completed",
            artifact={"outline_foundation_keys": sorted(foundation.keys())},
        )
        self._mark_phase(
            checkpoint,
            "character_roster",
            "completed",
            artifact={"character_count": len(roster)},
        )

    def _ensure_chapter_window(
        self,
        checkpoint: _BootstrapCheckpoint,
        chapter_numbers: list[int],
    ) -> None:
        if self._phase_status(checkpoint, "chapter_window") in {
            "completed",
            "adopted",
        }:
            return
        from packages.story_core.outline_rolling_store import RollingOutlineStore

        store = RollingOutlineStore(self._root)
        existing = store.read_rolling_outline() or {"chapters": []}
        existing_numbers = {
            int(chapter.get("chapter_number"))
            for chapter in existing.get("chapters", [])
            if isinstance(chapter, dict)
            and isinstance(chapter.get("chapter_number"), int)
        }
        manual_numbers = {
            int(chapter.get("chapter_number"))
            for chapter in existing.get("chapters", [])
            if isinstance(chapter, dict)
            and chapter.get("source") == "manual"
            and isinstance(chapter.get("chapter_number"), int)
        }
        missing = [number for number in chapter_numbers if number not in existing_numbers]
        # The user's manual edits are adopted as-is; the
        # generator must not produce rows for them.
        missing = [number for number in missing if number not in manual_numbers]
        if not missing:
            self._mark_phase(
                checkpoint,
                "chapter_window",
                "adopted",
                artifact={"source": "already_filled"},
            )
            return

        volume_range = self._volume_range(missing)
        context = self._rolling_context()
        character_cards = self._rolling_character_cards()
        rows = self._rolling_generator.generate(
            context=context,
            chapter_numbers=missing,
            volume_range=volume_range,
            character_cards=character_cards,
        )
        if not isinstance(rows, list):
            raise _BootstrapFailure(
                "chapter_window",
                "rolling_window_generator_returned_invalid_batch",
            )
        try:
            from packages.story_core.outline_rolling import validate_rolling_batch

            validate_rolling_batch(
                rows,
                expected_chapter_numbers=missing,
                volume_range=volume_range,
            )
        except ValueError as exc:
            raise _BootstrapFailure(
                "chapter_window",
                f"rolling_batch_validation_failed:{exc}",
            )
        written = store.apply_rolling_batch(
            chapters=rows,
            expected_chapter_numbers=missing,
            volume_range=volume_range,
        )
        self._mark_phase(
            checkpoint,
            "chapter_window",
            "completed",
            artifact={
                "written_chapter_numbers": list(written),
                "volume_range": list(volume_range),
            },
        )

    def _ensure_readiness(self, checkpoint: _BootstrapCheckpoint) -> None:
        result = validate_continuation_bootstrap(self._root)
        if not result.ready:
            raise _BootstrapFailure(
                "readiness_check",
                "readiness_check_failed:" + ",".join(result.errors),
            )
        self._mark_phase(
            checkpoint,
            "readiness_check",
            "completed",
            artifact={
                "ready": True,
                "next_chapter": result.next_chapter,
            },
        )

    # -- helpers ---------------------------------------------------------

    def _read_continuation_analysis(self) -> dict[str, Any]:
        path = self._root / ".story-system" / "continuation-analysis.json"
        payload = _read_json(path)
        return payload if isinstance(payload, dict) else {}

    def _compute_fingerprint(self, analysis: dict[str, Any]) -> str:
        project = _read_json(self._root / ".webnovel" / "project.json") or {}
        state = _read_json(self._root / ".webnovel" / "state.json") or {}
        if not isinstance(project, dict):
            project = {}
        if not isinstance(state, dict):
            state = {}
        continuation = (
            project.get("continuation")
            if isinstance(project.get("continuation"), dict)
            else {}
        )
        fingerprint_source = {
            "source_fingerprint": continuation.get("source_fingerprint", ""),
            "continuation_point": continuation.get("start_after_chapter", 0),
            "novel_type_id": (
                (project.get("world_blueprint") or {}).get("genre_plugin_ids", [""])[0]
                if isinstance(project.get("world_blueprint"), dict)
                else ""
            ),
            "analysis_confirmed": analysis.get("story_overview", "")[:200],
        }
        encoded = json.dumps(
            fingerprint_source,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
        return hashlib.sha256(encoded).hexdigest()

    def _adopt_existing_layers(
        self, checkpoint: _BootstrapCheckpoint
    ) -> None:
        # The current disk state may already pass the
        # readiness validator; adopt each layer so we never
        # overwrite approved data.
        if self._outline_layers_already_valid():
            if self._phase_status(checkpoint, "outline_foundation") == "pending":
                self._mark_phase(
                    checkpoint,
                    "outline_foundation",
                    "adopted",
                    artifact={"source": "imported_baseline"},
                )
            if self._phase_status(checkpoint, "character_roster") == "pending":
                self._mark_phase(
                    checkpoint,
                    "character_roster",
                    "adopted",
                    artifact={"source": "imported_baseline"},
                )

    def _outline_layers_already_valid(self) -> bool:
        outline = _read_json(self._root / ".webnovel" / "outline.json")
        if not isinstance(outline, dict):
            return False
        overall = outline.get("overall")
        arcs = outline.get("arcs")
        if not isinstance(overall, dict) or not str(overall.get("story") or "").strip():
            return False
        if not isinstance(arcs, list) or not arcs:
            return False
        return True

    def _current_chapter(self) -> int:
        state = _read_json(self._root / ".webnovel" / "state.json")
        if isinstance(state, dict):
            try:
                value = int(state.get("current_chapter") or 0)
            except (TypeError, ValueError):
                value = 0
            if value > 0:
                return value
        project = _read_json(self._root / ".webnovel" / "project.json")
        if isinstance(project, dict):
            try:
                value = int(project.get("current_chapter") or 0)
            except (TypeError, ValueError):
                value = 0
            if value > 0:
                return value
        return 0

    def _volume_range(self, chapter_numbers: list[int]) -> tuple[int, int]:
        project = _read_json(self._root / ".webnovel" / "project.json")
        ceiling = 0
        if isinstance(project, dict):
            outline = _read_json(self._root / ".webnovel" / "outline.json")
            if isinstance(outline, dict):
                overall = outline.get("overall")
                if isinstance(overall, dict):
                    try:
                        ceiling = int(overall.get("extension_ceiling_chapter") or 0)
                    except (TypeError, ValueError):
                        ceiling = 0
        start = chapter_numbers[0]
        end = max(chapter_numbers[-1], ceiling or chapter_numbers[-1])
        return (start, end)

    def _rolling_context(self) -> dict[str, Any]:
        project = _read_json(self._root / ".webnovel" / "project.json") or {}
        outline = _read_json(self._root / ".webnovel" / "outline.json") or {}
        analysis = self._read_continuation_analysis()
        state = _read_json(self._root / ".webnovel" / "state.json") or {}
        if not isinstance(project, dict):
            project = {}
        if not isinstance(outline, dict):
            outline = {}
        if not isinstance(state, dict):
            state = {}
        return {
            "active_arc": _find_active_arc(
                outline.get("arcs") if isinstance(outline.get("arcs"), list) else [],
                self._current_chapter(),
            ),
            "current_chapter": self._current_chapter(),
            "next_chapter": self._current_chapter() + 1,
            "direction": (
                project.get("current_focus")
                or (analysis.get("continuation_start") or {}).get("guidance", "")
                or ""
            ),
            "open_hooks": [
                item.get("text", "")
                for item in state.get("foreshadowing", [])
                if isinstance(item, dict)
                and str(item.get("status", "")) in {"open", "reinforced"}
            ],
            "world_rules": (
                (project.get("world_blueprint") or {}).get("world_rules", [])
                if isinstance(project.get("world_blueprint"), dict)
                else []
            ),
        }

    def _rolling_character_cards(self) -> list[dict[str, Any]]:
        project = _read_json(self._root / ".webnovel" / "project.json") or {}
        cards = (
            project.get("character_profiles")
            if isinstance(project.get("character_profiles"), list)
            else []
        )
        return [dict(card) for card in cards if isinstance(card, dict)]

    def _call_planning_generator(self) -> dict[str, Any]:
        """Invoke the injected planning generator.

        The bootstrapper accepts any object that exposes
        ``generate_outline_plan`` (the ``FileProjectStore``
        method) or ``generate`` (the lower-level
        ``LLMOutlinePlanningGenerator`` API). The wrapper
        always passes ``mode="regenerate"`` and
        ``persist_chapter_window=False`` so the legacy outline
        never grows a fabricated future plot.
        """

        from packages.story_core.file_project_store import FileProjectStore

        store = FileProjectStore(self._root)
        generator = self._planning_generator
        if hasattr(generator, "generate_outline_plan"):
            return generator.generate_outline_plan(
                store,
                mode="regenerate",
                guidance="",
                persist_chapter_window=False,
            )
        if callable(generator):
            return generator(
                store,
                mode="regenerate",
                guidance="",
                persist_chapter_window=False,
            )
        raise _BootstrapFailure(
            "outline_foundation",
            "planning_generator_not_callable",
        )

    def _mark_world_ready(self) -> None:
        project_path = self._root / ".webnovel" / "project.json"
        project = _read_json(project_path)
        if not isinstance(project, dict):
            return
        project["pipeline_stage"] = "world_ready"
        _write_json_atomic(project_path, project)


class _BootstrapFailure(Exception):
    def __init__(self, phase: str, error: str) -> None:
        super().__init__(error)
        self.phase = phase
        self.error = error


def _find_active_arc(arcs: list[Any], chapter_number: int) -> dict[str, Any]:
    for arc in arcs:
        if not isinstance(arc, dict):
            continue
        start = arc.get("start_chapter")
        end = arc.get("end_chapter")
        if (
            isinstance(start, int)
            and isinstance(end, int)
            and start <= chapter_number <= end
        ):
            return dict(arc)
    return {}
